apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-manager-deployment
  labels:
    app: job-manager
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-manager
  template:
    metadata:
      labels:
        app: job-manager
    spec:
      containers:
      - name: job-manager
        image: 15012013/job-manager:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 455Mi
          limits:
            cpu: 200m
            memory: 1Gi
        ports:
          - containerPort: 5089
---
apiVersion: v1
kind: Service
metadata:
  name: job-manager-clusterip-svc
  namespace: application
spec:
  selector:
    app: job-manager
  ports:
    - name: job-manager
      protocol: TCP
      port: 5091
      targetPort: 5091