apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  namespace: application
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /api/tookan
        pathType: Prefix
        backend:
          service:
            name: tookan-clusterip-svc
            port: 
              number: 5089
      - path: /api/new
        pathType: Prefix
        backend:
          service:
            name: news-manager-clusterip-svc
            port: 
              number: 5092
      - path: /api/campaign
        pathType: Prefix
        backend:
          service:
            name: campaign-manager-clusterip-svc
            port: 
              number: 5080
      - path: /api/customer
        pathType: Prefix
        backend:
          service:
            name: customer-manager-clusterip-svc
            port: 
              number: 5076
      - path: /api/email
        pathType: Prefix
        backend:
          service:
            name: email-service-clusterip-svc
            port: 
              number: 5058
      - path: /api/email
        pathType: Prefix
        backend:
          service:
            name: people-manager-clusterip-svc
            port: 
              number: 5055
      - path: /api/deliver
        pathType: Prefix
        backend:
          service:
            name: people-manager-clusterip-svc
            port: 
              number: 5055
      - path: /api/account
        pathType: Prefix
        backend:
          service:
            name: slack-service-clusterip-svc
            port: 
              number: 5074
      - path: /api/contact
        pathType: Prefix
        backend:
          service:
            name: contact-manager-clusterip-svc
            port: 
              number: 5075
      - path: /api-docs
        pathType: Prefix
        backend:
          service:
            name: campaign-manager-clusterip-svc
            port: 
              number: 5080
  ingressClassName: nginx