apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  namespace: application
spec:
  rules:
  - host: *
    http:
      paths:
      - path: /api/tookan
        pathType: Prefix
        backend:
          service:
            name: tookan-clusterip-svc
            port: 
              number: 5089
      - path: /api/new/load/byuser
        pathType: Prefix
        backend:
          service:
            name: news-manager-clusterip-svc
            port: 
              number: 5092
      - path: /api-docs
        pathType: Prefix
        backend:
          service:
            name: news-manager-clusterip-svc
            port: 
              number: 5092
  ingressClassName: nginx