apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  namespace: application
spec:
  rules:
  - host: a0016b4b0150840779aed112d394d0c7-1701272994.us-east-1.elb.amazonaws.com
    http:
      paths:
      - path: /api/tookan
        pathType: Prefix
        backend:
          service:
            name: tookan-clusterip-svc
            port: 
              number: 5089
      - path: [
          /api/new/markread,
          /api/new/load/byuser
        ]
        pathType: Prefix
        backend:
          service:
            name: news-manager-clusterip-svc
            port: 
              number: 5092
      - path: /api-docs
        pathType: Prefix
        backend:
          service:
            name: news-manager-clusterip-svc
            port: 
              number: 5092
  ingressClassName: nginx