apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-manager-deployment
  labels:
    app: fraud-detection-manager
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection-manager
  template:
    metadata:
      labels:
        app: fraud-detection-manager
    spec:
      containers:
      - name: fraud-detection-manager
        image: 15012013/fraud-detection-manager:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 200M
          limits:
            cpu: 500m
            memory: 512M
        ports:
          - containerPort: 5092
        # livenessProbe:
        #   httpGet:
        #     path: /api/health-check
        #     port: 5089
          # initialDelaySeconds: 3
          # periodSeconds: 3
          # failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-manager-clusterip-svc
  namespace: application
spec:
  selector:
    app: fraud-detection-manager
  ports:
    - name: fraud-detection-manager
      protocol: TCP
      port: 5092
      targetPort: 5092