apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kakfa-strimzi
  namespace: kafka
spec:
  kafka:
    template:
      pod: 
        securityContext:
          runAsUser: 0 
    config:
      auto.create.topics.enable: false
      log.message.format.version: "2.3"
      log.retention.bytes: 1073741824
      log.retention.hours: 1
      log.retention.check.interval.ms: 300000
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 1
    resources: {}
    storage:
      class: kafka-ssd
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
  zookeeper:
    template:
      pod: 
        securityContext:
          runAsUser: 0 
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 1
    resources:
      requests:
        cpu: 1
        memory: 3Gi
      limits:
        cpu: 1
        memory: 3Gi
    storage:
      class: zookeeper-ssd
      deleteClaim: false
      size: 10Gi
      type: persistent-claim