apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-ssd
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: zookeeper-ssd
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ka-pv1
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  storageClassName: kafka-ssd
  hostPath:
    path: "/mnt/data/zookeeper"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zo-pv1
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  storageClassName: zookeeper-ssd
  hostPath:
    path: "/mnt/data/zookeeper"
