apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-manager-deployment
  labels:
    app: news-manager
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-manager
  template:
    metadata:
      labels:
        app: news-manager
    spec:
      containers:
      - name: news-manager
        image: 15012013/news-manager:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 200M
          limits:
            cpu: 1
            memory: 512M
        ports:
          - containerPort: 5089
        # livenessProbe:
        #   httpGet:
        #     path: /api/health-check
        #     port: 5089
          # initialDelaySeconds: 3
          # periodSeconds: 3
          # failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: news-manager-clusterip-svc
  namespace: application
spec:
  selector:
    app: news-manager
  ports:
    - name: news-manager
      protocol: TCP
      port: 5091
      targetPort: 5091