apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service-deployment
  labels:
    app: authentication-service
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: 15012013/authentication-service:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 200M
          limits:
            cpu: 500m
            memory: 512M
        ports:
          - containerPort: 5056
        # livenessProbe:
        #   httpGet:
        #     path: /api/health-check
        #     port: 5089
          # initialDelaySeconds: 3
          # periodSeconds: 3
          # failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service-clusterip-svc
  namespace: application
spec:
  selector:
    app: authentication-service
  ports:
    - name: authentication-service
      protocol: TCP
      port: 5056  
      targetPort: 5056