apiVersion: apps/v1
kind: Deployment
metadata:
  name: tookan-deployment
  labels:
    app: tookan
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tookan
  template:
    metadata:
      labels:
        app: tookan
    spec:
      containers:
      - name: tookan
        image: 15012013/tookan:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 200Mi
          limits:
            cpu: 1500m
            memory: 512Mi
        ports:
          - containerPort: 5089
        livenessProbe:
          httpGet:
            path: /api/health-check
            port: 5089
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
---

kubectl get pod tookan-deployment-d5794548-kvmxs --output=yaml -n application


kubectl get pod tookan-deployment-d5794548-kvmxs -o go-template='{{range .status.containerStatuses}}{{printf "%s:\n%s\n\n" .name .lastState.terminated.message}}{{end}}'

apiVersion: v1
kind: Service
metadata:
  name: tookan-clusterip-svc
  namespace: application
spec:
  selector:
    app: tookan
  ports:
    - name: job
      protocol: TCP
      port: 5089
      targetPort: 5089