apiVersion: apps/v1
kind: Deployment
metadata:
  name: tookan-deployment
  labels:
    app: tookan
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tookan
  template:
    metadata:
      labels:
        app: tookan
    spec:
      containers:
      - name: tookan
        image: 15012013/tookan:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 200Mi
          limits:
            cpu: 1.5
            memory: 512Mi
        ports:
          - containerPort: 5089
        # livenessProbe:
        #   httpGet:
        #     path: /api/health-check
        #     port: 5089
          # initialDelaySeconds: 3
          # periodSeconds: 3
          # failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: tookan-clusterip-svc
  namespace: application
spec:
  selector:
    app: tookan
  ports:
    - name: tookan
      protocol: TCP
      port: 5089
      targetPort: 5089